### PR TITLE
Upgrade this project with Angular 5 and nativescript 3.4

### PR DESCRIPTION
**Pull request by govi2010**
I have update project to latest release of native script

### CODE REVIEW

**Comment by BasyaLipman** [comment]
Hey @govi2010 - thanks for submitting this, it's needed.

I actually took your PR locally just to test and play around, but couldn't get the thing to run for mobile.

On web all looks great, but when running `npm run android.phone` I get the following:

`Error: ENOENT: no such file or directory, stat '/Users/.../Source/test-3/nativescript/src/fonts'`

And I see that in fact the fonts folder is not in the `nativescript` folder. Neither is the `assets` folder there.

Do you know how this happened?

Thanks!

**Comment by megamindbrian** [comment]
Ran into this bug trying to apply updates manually. 
https://github.com/NativeScript/nativescript-cli/pull/2473/files

**Comment by BasyaLipman** [comment]
Removing the symlinked assets and fonts folders (which were not showing in vscode but could be found in the finder) and then re-running `node symlink.js` worked to solve this issue. Just in case anyone else comes across this behavior.

**Comment by anandt2003** [comment]
@BasyaLipman so the PR will be accepted ? If it’s working and if it can be merged, will be easy for others to clone.

**Comment by govi2010** [comment]
@BasyaLipman  I let me know if you need anything from my side.

**Comment by jdnichollsc** [comment]
@sean-perkins hi bro, what do you think about this PR? :)

**Comment by sean-perkins** [comment]
@govi2010 Thanks for going through this. I pulled in a bit of what you did and also reflected current changes. All of that is now in master. Thank you for your contribution!

**Pull request closed without merging**
